### ISSUE TITLE
【TODO】账号登录绑定相关

### ISSUE THREAD

**Issue by msojocs** [WeCuit/WeCuit-Spring#18]
- [x] 微信：生成30位 `token` 并与 `用户ID` 绑定，返回小程序码

- [x] QQ ：生成 `token` 并与 `用户ID` 绑定，返回 `appid` 与 `含有token的path` 
- [x] 检测`token`有效性
- [x] 有效时，绑定账号
- [x] 小程序端绑定账号
